#!/usr/bin/env python3
"""WP7a visualization tests (registered with ctest, run by CMake's python3).

  test_viz.py <repo_root>

Checks (returns non-zero on any failure, R4):
  1. Regenerating from the committed CSVs produces every expected file.
  2. Each SVG is well-formed XML, is ASCII-only, and carries its source CSV
     name, the master seed, and the schema_version in its caption.
  3. No stub markers (TODO/FIXME/XXX/TBD) and no wall-clock timestamps appear
     (spec v4.2 R6). Rate figures name their Wilson interval; the keep-out
     figure carries the "not a flight safety certificate" disclaimer.
  4. The regenerated bytes match the committed generated/viz exactly
     (reproducibility -- the same contract CI enforces with git diff).
"""
import os
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

EXPECTED = [
    "wp5_outcomes.svg", "wp5_dv_percentiles.svg", "wp5_removals_percentiles.svg",
    "wp5_sync_time_percentiles.svg", "wp5_keepout_rate.svg",
    "wp6_amortization.svg", "wp6_tornado.svg", "wp6_fom_weightings.svg",
    "wp3_decay_trade.svg", "wp5_dashboard.html",
]
STUB_MARKERS = ("TODO", "FIXME", "XXX", "TBD")
TIMESTAMP_MARKERS = ("2026-", "2027-", "UTC", "GMT", "generated at", "generated on")

fails = []
def check(cond, msg):
    if not cond:
        fails.append(msg)

def main():
    if len(sys.argv) < 2:
        print("usage: test_viz.py <repo_root>", file=sys.stderr)
        return 2
    repo = sys.argv[1]
    make = os.path.join(repo, "tools", "viz", "make_viz.py")
    committed = os.path.join(repo, "generated", "viz")

    tmp = tempfile.mkdtemp(prefix="wp7a_viz_")
    r = subprocess.run([sys.executable, make, repo, tmp],
                       capture_output=True, text=True)
    check(r.returncode == 0, f"make_viz failed: {r.stderr.strip()}")

    for name in EXPECTED:
        path = os.path.join(tmp, name)
        check(os.path.exists(path), f"missing regenerated {name}")
        if not os.path.exists(path):
            continue
        txt = open(path, encoding="utf-8").read()

        # ASCII-only (R11).
        try:
            txt.encode("ascii")
        except UnicodeEncodeError:
            check(False, f"{name}: non-ASCII content")

        # No stub markers / timestamps (R6, v4.2).
        for m in STUB_MARKERS + TIMESTAMP_MARKERS:
            check(m not in txt, f"{name}: contains forbidden marker '{m}'")

        if name.endswith(".svg"):
            try:
                ET.fromstring(txt)
            except ET.ParseError as e:
                check(False, f"{name}: not well-formed XML ({e})")
            # caption provenance: source CSV name + schema + seed.
            check(".csv" in txt, f"{name}: no source CSV named")
            check("schema" in txt, f"{name}: no schema_version")
            check(("0x" in txt) or ("seed n/a" in txt), f"{name}: no master seed")

    # Rate figures must name the Wilson interval.
    ko = open(os.path.join(tmp, "wp5_keepout_rate.svg"), encoding="utf-8").read()
    check("Wilson" in ko, "keepout: no Wilson interval named")
    check("not a flight safety certificate" in ko,
          "keepout: missing 'not a flight safety certificate' disclaimer")

    # Reproducibility: regenerated bytes == committed bytes.
    for name in EXPECTED:
        cpath = os.path.join(committed, name)
        tpath = os.path.join(tmp, name)
        if not os.path.exists(cpath):
            check(False, f"committed generated/viz/{name} is missing")
            continue
        if not os.path.exists(tpath):
            continue
        with open(cpath, "rb") as a, open(tpath, "rb") as b:
            cb, tb = a.read(), b.read()
        # normalize CRLF->LF so a Windows checkout of the committed file still
        # matches the LF the generator writes (CI enforces raw bytes via git).
        check(cb.replace(b"\r\n", b"\n") == tb,
              f"{name}: committed bytes != regenerated (reproducibility)")

    if fails:
        for f in fails:
            print("FAIL:", f)
        print(f"viz: {len(fails)} failure(s)")
        return 1
    print(f"viz: all checks passed ({len(EXPECTED)} artifacts)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
